### ISSUE TITLE
Problem in Windows 10

### ISSUE THREAD

**Issue by Vilumbre** [Cryptix720/HUDINX#1]
Hello Cryptix720, my question is: How do I install in windows 10?.

**Comment by Cryptix720** [comment]
Hi Vilumbre!

## Steps to Reproduce:
If you having an issue with the installation on Windows 10:

(!root) KILL.sh : use this to kill any hudinx activities.

1. sh UNINSTALL.sh
2. run the INSTALL.sh as admin.
3. run LAUNCH.sh

## Python
For python problems: Use Python 2.7+ for this project. 

## Tips
This project is in zombie-development use this with your own powers for greater code force!
